datasources:
  default:
    url: jdbc:h2:mem:cnutscheduleproxy;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: cnutscheduleproxy
    password: ''
    poolName: Hikari
    autoCommit: false

jpa:
  default:
    packages-to-scan:
      - com.cnut.schedule.domain
      - com.cnut.schedule.repository
    properties:
      hibernate:
        hbm2ddl:
          auto: create-drop

micronaut:
  security:
    enabled: true

cnutschedule:
  clientApp:
    name: 'cnutscheduleproxyApp'
  logging:
    # To test json console appender
    use-json-format: true # By default, logs are in Json format
    # To test logstash appender
    logstash:
      enabled: true
      host: localhost
      port: 5000
      queue-size: 512
  mail:
    from: test@localhost
    base-url: http://127.0.0.1:8080
  metrics:
    logs: # Reports metrics in the logs
      enabled: true
      report-frequency: 60 # in seconds
