---
micronaut:
  application:
    name: cnut-schedule-proxy

---
cnut-schedule-proxy:
  api:
    dekanat:
      base-url: https://vnz.osvita.net/BetaSchedule.asmx

---
micronaut:
  http:
    client:
      read-timeout: 25s
  router:
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger/
        mapping: /swagger/**
      swagger-ui:
        paths: classpath:META-INF/swagger/views/swagger-ui
        mapping: /swagger-ui/**
  security:
    enabled: true
    endpoints:
      login:
        enabled: true
    token:
      jwt:
        enabled: true
        signatures:
          secret:
            generator:
              secret: 0c22c1c1-76d0-4c60-9a0d-d9d05505e75f
      writer:
        header:
          enabled: true
          headerName: "Authorization"
          prefix: "Bearer "

credentials:
  users:
    test: test123
  roles:
    test: ADMIN
