openapi: 3.0.1
info:
  title: cnut-schedule-proxy
  version: "0.0"
paths:
  /api/schedule/{uniId}/filters:
    get:
      operationId: getFiltersData
      parameters:
      - name: uniId
        in: path
        required: true
        schema:
          type: string
      responses:
        default:
          description: getFiltersData default response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FiltersData'
  /api/schedule/{uniId}/faculties:
    get:
      operationId: getFaculties
      parameters:
      - name: uniId
        in: path
        required: true
        schema:
          type: string
      responses:
        default:
          description: getFaculties default response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Faculty'
  /api/schedule/{uniId}/courses:
    get:
      operationId: getCourses
      parameters:
      - name: uniId
        in: path
        required: true
        schema:
          type: string
      responses:
        default:
          description: getCourses default response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Course'
  /api/schedule/{uniId}/educ-forms:
    get:
      operationId: getEducationForms
      parameters:
      - name: uniId
        in: path
        required: true
        schema:
          type: string
      responses:
        default:
          description: getEducationForms default response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/EducForm'
  /api/schedule/{uniId}/faculties/{facultyId}/study-groups:
    get:
      operationId: getFacultyStudyGroups
      parameters:
      - name: uniId
        in: path
        required: true
        schema:
          minLength: 1
          type: string
      - name: facultyId
        in: path
        required: true
        schema:
          minLength: 1
          type: string
      - name: facultyGroupsFilter
        in: query
        required: true
        explode: true
        schema:
          $ref: '#/components/schemas/FacultyGroupsFilter'
      responses:
        default:
          description: getFacultyStudyGroups default response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FacultyStudyGroups'
  /api/schedule/{uniId}/study-groups/{groupId}/schedule-data:
    get:
      operationId: getFacultyStudyGroups
      parameters:
      - name: uniId
        in: path
        required: true
        schema:
          minLength: 1
          type: string
      - name: groupId
        in: path
        required: true
        schema:
          minLength: 1
          type: string
      - name: groupClassesFilter
        in: query
        required: true
        explode: true
        schema:
          $ref: '#/components/schemas/GroupClassesFilter'
      responses:
        default:
          description: getFacultyStudyGroups default response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ScheduleDataRow'
components:
  schemas:
    BaseResponse:
      type: object
      properties:
        type:
          type: string
    FiltersData:
      allOf:
      - $ref: '#/components/schemas/BaseResponse'
      - type: object
        properties:
          faculties:
            type: array
            items:
              $ref: '#/components/schemas/Faculty'
          educForms:
            type: array
            items:
              $ref: '#/components/schemas/EducForm'
          courses:
            type: array
            items:
              $ref: '#/components/schemas/Course'
    Faculty:
      type: object
      properties:
        key:
          type: string
        value:
          type: string
    EducForm:
      type: object
      properties:
        key:
          type: string
        value:
          type: string
    Course:
      type: object
      properties:
        key:
          type: string
        value:
          type: string
    FacultyStudyGroups:
      allOf:
      - $ref: '#/components/schemas/BaseResponse'
      - type: object
        properties:
          studyGroups:
            type: array
            items:
              $ref: '#/components/schemas/StudyGroup'
          studyTypes:
            type: array
            items:
              $ref: '#/components/schemas/StudyType'
    StudyGroup:
      type: object
      properties:
        key:
          type: string
        value:
          type: string
    StudyType:
      type: object
      properties:
        key:
          type: string
        value:
          type: string
    FacultyGroupsFilter:
      type: object
      properties:
        uniId:
          type: string
        facultyId:
          type: string
        educationForm:
          type: string
        courseId:
          type: string
        giveStudyTypes:
          type: boolean
    ScheduleDataRow:
      type: object
      properties:
        studyTime:
          type: string
        studyTimeBegin:
          type: string
        studyTimeEnd:
          type: string
        weekDay:
          type: string
        fullDate:
          type: string
        discipline:
          type: string
        studyType:
          type: string
        cabinet:
          type: string
        employee:
          type: string
        studySubgroup:
          $ref: '#/components/schemas/Object'
    Object:
      type: object
    GroupClassesFilter:
      required:
      - groupId
      - uniId
      type: object
      properties:
        uniId:
          minLength: 1
          type: string
        groupId:
          minLength: 1
          type: string
        startDate:
          type: string
        endDate:
          type: string
        studyTypeId:
          type: string
